Repository smaranjitghose/auto_vaidya, pull requests merged in 2020-09, with the labels that each got.

#43 Solved #17 Added new logo for the application
  logo_design/autoVadiyaLogo.png
Labels: PR: unreviewed

#47 updated the contributing file
  CONTRIBUTING.md
Labels: CH-20, ReadMe

#49 GIFs and SVGs for logo
  logo_design/Auto-Vaidya-Dark-Aniruddh.svg
  logo_design/Auto-Vaidya-Light-Aniruddh.svg
  logo_design/AutoVaidyaGIFDark.gif
  logo_design/AutoVaidyaGIFLight.gif
  logo_design/auto vaidya Aniruddh static.png
Labels: CH-20, Medium

#50 Diabetes pred
  diabetes/Diabetes_Prediction.ipynb
  diabetes/Results.md
  diabetes/test/models/knn.pkl
  diabetes/test/models/logreg.pkl
  diabetes/test/models/svc.pkl
  diabetes/test/models/tree.pkl
  diabetes/test/models/xgb.pkl
  diabetes/test/test.py
Labels: CH-20, Medium

#63 Solved #58 Added : contact form
  assets/css/contact.css
  assets/js/contact.js
  contact.html
Labels: CH-20, Easy

#67 Streamlit app for skin cancer detection
  README.md
  app.py
  skin_cancer_mnist.py
Labels: CH-20, Easy
