Repository smaranjitghose/auto_vaidya, pull requests merged in 2020-08, with the labels that each got.

#9 Solved #8 : Moved JS code from index.html to separate .js file in assets.
  assets/js/script.js
  index.html
Labels: PR: unreviewed, enhancement, good first issue, hackincodes20

#11 Added : Contact page with form validation
  assets/css/style_form.css
  assets/js/script_form.js
  contact.html
Labels: CH-20, PR: unreviewed, enhancement

#13 Solved #12 : Added a footer
  assets/css/materialize.min.css
  index.html
Labels: PR: unreviewed

#10 Create Feature.request.md
  .github/Feature.request.md
Labels: PR: unreviewed

#15 solved #14 Added : 404 Error page
  404.html
  assets/css/style_404.css
Labels: CH-20, PR: unreviewed

#21 solved #19 Added : splash screen
  assets/css/style.css
  assets/images/splash.gif
  assets/js/materialize.min.js
  assets/js/script.js
  index.html
Labels: CH-20, Easy

#20 Cards modified
  assets/css/style.css
  index.html
Labels: CH-20, Easy, PR: reviewed-changes-requested

#32 Logo samples added
  .github/Feature.request.md
  404.html
  LICENSE
  README.md
  assets/css/materialize.min.css
  assets/css/style.css
  assets/css/style_404.css
  assets/css/style_form.css
  assets/images/3680924.svg
  assets/images/Patreon-Logo_Black.png
  assets/images/Patreon-Logo_FieryCoral.png
  assets/images/Patreon-Logo_White.png
  assets/images/anush_bhatia.png
  assets/images/bmc-new-btn-logo.svg
  assets/images/github.svg
  assets/images/hakin_codes.png
  assets/images/linkedin.svg
  assets/images/psoc_logo.png
  assets/images/smaranjitghose1.png
  assets/js/github.json
  assets/js/jquery.min.js
  assets/js/linkedin.json
  assets/js/materialize.min.js
  assets/js/script.js
  assets/js/script_form.js
  contact.html
  index.html
  logo_design/Logo 0Auto Vaidya_shraddhavp.png
  logo_design/Logo 0Auto Vaidya_shraddhavp.svg
  logo_design/Logo 1Auto Vaidya_shraddhavp.png
  logo_design/Logo 1Auto Vaidya_shraddhavp.svg
  logo_design/desktop.ini
Labels: CH-20, Hard, PR: reviewed-approved

#42 Added the logo samples
  logo_design/Logo_yash.png
  logo_design/Logo_yash.svg
Labels: CH-20, Medium
